language: ruby
cache: bundler
bundler_args: --jobs=8 --without development production
services:
  - elasticsearch
before_script:
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
script:
  - bundle exec rspec
notifications:
  slack:
    secure: R2FlMp3wtdiaqtYVl5NrPQApbeXC1dGwGN8QYok3wjS/zC4ydQBQt9oD1La7IMMkOrN/ZyFJMDw5M4d2E/gArxuXs79qcBSzIro0/e+mxZ+g9VR2W5tPVuT9GH4GB0kKaJC55aTHJSGG7518fAsmPyEBmIcX2P6CNwnkiW1u9mRtc28NMWs21RhqKVYf6828l4yz2j8pbGZIeIoOKii2q2PAd3F1X7Bi4C3Ljnm9n3ed8nXhnojGPmcc+PUWAw93JH8TYXxc5v0Qi9Rx9mltsLajReLAqj0EJFHuVKs77+comauqWSNyr5BurABujXFa/Hu7jt6IASXSseq7xdVjBxPmUoD1rVyEOj/pDckoTX/hCZBB/9cTIBZVe2gIkkPuxojmz1wwSlAcHAAOZQ0ZMYycj41SZlMIKzeeby7JA3j2llmVawQD/EytK3noYTbUZY2WYBNRP692RuB4l7Gg1WfayiIU2TG6G/14d95IF6ACsTUNlflarZvfzPLvW8BJ3NdjaHrSweZzkVinooAzGkIqEGDzAaw6I1NVQ4J+j2LhGF45MaZcJDhiRSE07859fsRyIGo3PVJMandWpiuuIgCN2tfQwhSfZ27F0Wth0MhcEREAzhxxnKd5XHbRGuApKfIfOtUXcKJDhHlG3+7r0KNlDmzP3SruO7+uc/Buu5g=
