db:
  image: postgres

elasticsearch:
  image: elasticsearch:1.7.2

kibana:
  image: kibana
  links:
    - elasticsearch
  ports:
    - 8081:5601

redis:
  image: redis

web:
  build: .
  links:
    - db
    - elasticsearch
    - redis
  env_file: docker-dev.env
  ports:
    - 8080:80

sidekiq:
  build: .
  command: bundle exec sidekiq
  links:
    - db
    - elasticsearch
    - redis
  env_file: docker-dev.env
