version: '2.0'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:2.3
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    image: instedd/telemetry-kibana:4.5
    env_file: docker-dev.env
    links:
      - elasticsearch

  redis:
    image: redis

  web:
    extends:
      file: docker-compose-base.yml
      service: rails
    command: bundle exec rails server -b 0.0.0.0
    links:
      - db
      - redis
      - elasticsearch
      - kibana
    ports:
      - 3000:3000

  sidekiq:
    extends:
      file: docker-compose-base.yml
      service: rails
    command: bundle exec sidekiq
    links:
      - db
      - elasticsearch
      - redis

volumes:
  db:
  elastic:
  redis:
  bundle:
