version: '2'

services:
  rails:
    image: instedd/nginx-rails:2.2
    env_file: docker-dev.env
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
