db:
  image: postgres
  volumes:
    - '/var/lib/postgresql/data'

elasticsearch:
  image: elasticsearch:2.1
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes:
    - '/usr/share/elasticsearch/data'
  ports:
    - 9200:9200

kibana:
  image: instedd/telemetry-kibana:4.3
  links:
    - elasticsearch
  ports:
    - 5601:5601

redis:
  image: redis

web:
  build: .
  links:
    - db
    - elasticsearch
    - redis
    - kibana
  env_file: docker-dev.env
  ports:
    - 80:80

sidekiq:
  build: .
  command: bundle exec sidekiq
  links:
    - db
    - elasticsearch
    - redis
  env_file: docker-dev.env
